format = """
$directory\
$git_branch\
$git_status\
$fill\
$dart\
$golang\
$java\
$kotlin\
$nodejs\
$php\
$python\
$ruby\
$rust\
$swift\
$terraform\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "#1e66f5"
truncation_length = 3
truncate_to_repo = false
format = "[ $path]($style)[$read_only]($read_only_style) "

[character]
success_symbol = "[❯](#40a02b)"
error_symbol = "[❯](#d20f39)"

[git_branch]
symbol = " "
format = "[~]($style) [$symbol$branch]($style) "
style = "#8839ef"

[git_status]
format = '([~ $all_status$ahead_behind]($style) )'
style = "#e64553"
ahead = "↑${count}"
behind = "↓${count}"
diverged = "↑${ahead_count}↓${behind_count}"
modified = " ${count}"
staged = " ${count}"
untracked = " ${count}"
deleted = " ${count}"
conflicted = " ${count}"
renamed = " ${count}"
stashed = " ${count}"

[cmd_duration]
format = "[~  $duration]($style)"
style = "#9ca0b0"
min_time = 2_000

[nodejs]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#40a02b"

[python]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#df8e1d"

[rust]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#fe640b"

[golang]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#04a5e5"

[java]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#d20f39"

[kotlin]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#8839ef"

[dart]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#209fb5"

[swift]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#fe640b"

[php]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#7287fd"

[ruby]
symbol = " "
format = "[~ $symbol$version]($style) "
style = "#d20f39"

[terraform]
symbol = "󱁢 "
format = "[~ $symbol$version]($style) "
style = "#8839ef"
